### ISSUE TITLE
CORS Thematik für Azure Functions prüfen

### ISSUE THREAD

**Issue by maltemorgenstern** [FAP-Cloud-Service/FAP-Infrastructure#18]
https://docs.microsoft.com/de-de/azure//azure-functions/functions-how-to-use-azure-function-app-settings?tabs=portal#cors
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#cors

Frontend muss Zugriff haben. Für Tests sollten die Anpassungen direkt im Portal vorgenommen werden.

**Comment by maltemorgenstern** [comment]
@leonschbbht wenn ich die Doku richtig verstehe kann standardmäßig jeder Requests machen - keine CORS Beschränkungen.

Wollen wir das nach dem nächsten Deployment angehen? Oder wäre das für dich ein must-have für's Release?

**Comment by leonschbbht** [comment]
Sounds Good.
Im ersten Schritt ausrollen und testen, dass die Grundfunktionalitäten gegeben sind, im nächsten Schritt die Sicherheitsaspekte klären. 👍🏼

**Comment by leonschbbht** [comment]
Ich glaube das haben wir geklärt :)
