### ISSUE TITLE
Manueller Workflow Trigger

### ISSUE THREAD

**Issue by leonschbbht** [FAP-Cloud-Service/FAP-Infrastructure#41]
Wie hier beschrieben:

[workflow_dispatch-Event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch)

[Manuell ausführen](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)

**Comment by maltemorgenstern** [comment]
@leonschbbht  Ich mache da mal  kurz noch einen PR für, dann können wir deployen
