### ISSUE TITLE
Azure Tables Datenbank mit Terraform aufsetzen

### ISSUE THREAD

**Issue by maltemorgenstern** [FAP-Cloud-Service/FAP-Infrastructure#9]
https://docs.microsoft.com/de-de/azure/azure-sql/database/serverless-tier-overview

**Comment by leonschbbht** [comment]
Probier mal die Antwort von abhidhar82 in diesem Thread aus:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/4185

```terraform
resource "azurerm_sql_database" "testdb" {
name = "testdb"
resource_group_name = "testrg"
location = ####
server_name = #####
create_mode = "Default"
edition = "GeneralPurpose"
max_size_bytes = "34359738368"
requested_service_objective_name = "GP_S_Gen5_${var.dbvcpu}"
}
```

[Terraform Doku](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database)


Wir sollten aber dennoch über eine NoSQL Datenbank nachdenken um Nicks Credits zu schonen.
Gewöhnlicherweise sind NoSQL DBs Pay Per Use.

Schau dir mal die [Azure Table](https://azure.microsoft.com/en-us/services/storage/tables/) NoSQL Lösung an
[Terraform Doku](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_table)

[C# Beispiel](https://www.c-sharpcorner.com/article/azure-storage-tables/)

**Comment by maltemorgenstern** [comment]
Der NoSQL Ansatz sieht auch sehr gut aus - werde ich mal ausprobieren.

**Comment by maltemorgenstern** [comment]
Siehe auch https://github.com/FAP-Cloud-Service/FAP-Backend/issues/14

**Comment by maltemorgenstern** [comment]
Tabellen werden via C'# Code erstellt - dann kann auch lokales Testen erfolgen.
